<a href="https://colab.research.google.com/github/Nivedita5/pytorch-deep-learning/blob/main/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#GPU Version

In [2]:
!nvidia-smi

/bin/bash: nvidia-smi: command not found


#Libraries

In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.0.1+cu118


#Introduction to Tensors

In [4]:
#Scalar

scalar= torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
scalar.item()

7

In [11]:
#Vector
vector= torch.tensor([7,7])
vector

tensor([7, 7])

In [9]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [12]:
# MATRIX
MATRIX= torch.tensor([[7,8],
                      [9,10]])

MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [13]:
MATRIX.ndim

2

In [15]:
MATRIX[0]
MATRIX[1]

tensor([ 9, 10])

In [16]:
MATRIX.shape

torch.Size([2, 2])

In [18]:
#Tensor

TENSOR= torch.tensor([[[1,2,3],
                       [3,6,9],
                       [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [19]:
TENSOR.ndim

3

In [20]:
TENSOR.shape

torch.Size([1, 3, 3])

In [21]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### RANDOM TENSORS

In [28]:
 random_tensor= torch.rand(3,4)
 random_tensor

tensor([[0.4901, 0.2977, 0.9207, 0.5057],
        [0.5687, 0.7701, 0.4362, 0.7133],
        [0.1783, 0.3701, 0.3509, 0.6556]])

In [30]:
random_image_size_tensor= torch.rand(size=(224,224,3))
random_image_size_tensor.ndim, random_image_size_tensor.shape

(3, torch.Size([224, 224, 3]))

### ZEROS AND ONES

In [31]:
# Zeros and Ones
zeros= torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [32]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [33]:
ones= torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [34]:
ones.dtype

torch.float32

In [35]:
random_tensor.dtype

torch.float32

### Creating range of TENSORS and TENSOR-like

In [42]:
one_to_ten= torch.arange(start=0, end=1000, step=77)
one_to_ten

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [43]:
#TENSORS-like

ten_zeros= torch.zeros_like(input= one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# TENSOR data-types

Common errors:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on right device

In [44]:
 float_32_tensor= torch.tensor([3.0, 6.0, 9.0], 
                               dtype=None,
                               device=None,
                               requires_grad=False)
 float_32_tensor

tensor([3., 6., 9.])

In [45]:
float_32_tensor.dtype

torch.float32

In [46]:
float_16_tensor= float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [49]:
float_mul= float_16_tensor*float_32_tensor
float_mul

tensor([ 9., 36., 81.])

In [50]:
float_mul.dtype

torch.float32

In [51]:
int_32_tensor= torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [52]:
float_32_tensor*int_32_tensor

tensor([ 9., 36., 81.])

### Getting Information

1. Tensors not right datatype- 'tensor.dtype'
2. Tensors not right shape- 'tensor.shape'
3. Tensors not on right device- 'tensor.device'

In [53]:
some_tensor= torch.rand(3,4)
some_tensor

tensor([[0.4087, 0.6441, 0.6521, 0.7482],
        [0.4404, 0.5520, 0.0259, 0.3117],
        [0.2605, 0.8563, 0.8437, 0.2195]])

In [54]:
print(f'Datatype : {some_tensor.dtype}')
print(f'Shape : {some_tensor.shape}')
print(f'Device : {some_tensor.device}')

Datatype : torch.float32
Shape : torch.Size([3, 4])
Device : cpu
